function bt_eval(k,p){try{return window.eval.apply(window,[k])}catch(t){p&&p(t)}}var bt_parameter=function(){var k;return function(p,t){var y=t||document;"undefined"===typeof k&&(k=new BrightTag.HTTP.URL(y.location.href));return k.param(p)}}();function bt_meta(k,p){for(var t,y=(p||document).getElementsByTagName("meta"),s=0,q=y.length;s<q;s++)if(t=y[s],t.getAttribute("name")===k)return t.getAttribute("content");return""}
function bt_cookie(k,p){return(new BrightTag.HTTP.Cookie(p||document)).get(k)||""}function bt_data(k,p){var t=BrightTag.instance||BrightTag.configuredSites()[0];return t?t.data(k,p):""}window.bt_data_escaped=bt_data;function bt_log(k){window.console&&console.log&&console.log("BrightTag: "+k)}var bt_handle_exception=bt_log;
window.BrightTag=function(k){function p(a,c){return Object.prototype.toString.call(a)==="[object "+c+"]"}function t(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")}function y(a){return"\n//at-sourceURL=/BrightTag/"+a.replace(/\s+/g,"_")+".js"}function s(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d]);return a}function q(a,c){if(a)if(n.isArray(a)||a.length){var d,b;d=0;for(b=a.length;d<b;d++)c(a[d],d)}else if(n.isObject(a))for(d in a)a.hasOwnProperty(d)&&c(d,a[d])}function M(a,c){var d=
[];q(n.isArray(a)?a:[a],function(a){c(a)&&d.push(a)});return d}function x(a,c){var d,b,g=n.isArray(a)?a:[a];d=0;for(b=g.length;d<b;d++)if(g[d]===c)return!0;return!1}function N(a){return!n.isString(a)?a:a.replace(/%/g,"%25").replace(/#/g,"%23").replace(/&/g,"%26").replace(/'/g,"%27").replace(/;/g,"%3B").replace(/</g,"%3C").replace(/>/g,"%3E")}function O(a){for(var c=5381,d=0,b=a.length;d<b;)c=(c<<5)+c+a.charCodeAt(d++);return c.toString(36)}function P(a){function c(){}function d(a){var b=Array.prototype.slice.call(arguments,
1);q(v,function(f){var m=[u].concat(b);(f[a]||c).apply(null,m)})}function b(){r=!0;J=k.length;d("engine:off")}function g(){r&&d("engine:on");r=!1;z=0;(k[J++]||b)()}function e(){d("block:finish");g()}function h(b,f){return function(){var m=!1,l,c=a.createElement("script");c.onload=c.onreadystatechange=function(){var a;if(!(a=m)){a:{switch(c.readyState){case void 0:case "loaded":case "complete":a=!0;break a}a=!1}a=!a}a||(m=!0,e())};c.onerror=function(){d("block:error",{type:"script",exception:"Problem loading "+
b});m||e()};c.src=b;f&&(c.text=f);d("block:start",b);l=a.getElementsByTagName("script")[0];l.parentNode.insertBefore(c,l)}}function f(b){return function(){try{if(d("block:start",b),n.isString(b)){var f=t(b).replace(/^\x3c!--/,"").replace(/--\x3e$/,"");a.defaultView?a.defaultView.eval.call(window,f):a.parentWindow?a.parentWindow.execScript(f):d("block:error",{type:"wait",exception:"Could not evaluate wait block ["+f+"]"})}else b()}catch(m){d("block:error",{type:"wait",exception:m})}finally{e()}}}function m(a){k.push(a);
r&&g();return u}function l(a){k.splice(J+z++,0,a);return u}var u=this,v=[],A={},r=!1,k=[],J=0,z=0;u.run=function(){d("engine:on");g()};u.options=function(a){s(A,a);return u};u.option=function(a){return A[a]};u.script=function(a){return m(h(a))};u.wait=function(a){return m(f(a))};u.preemptScript=function(a,b){return l(h(a,b))};u.preemptWait=function(a){return l(f(a))};u.listen=function(a){v.push(a);(a["engine:listen"]||c).apply(null,[u]);return u}}function R(a){function c(a){e.push(a);f&&!m&&b()}function d(a){a.run()}
function b(){var a=e[h];a&&(h++,a.listen(l).run())}var g,e=[],h=0,f=!1,m=!1,l={"engine:on":function(){m=!0},"engine:off":function(){m=!1;b()}};g=c;this.alwaysQueue=function(){g=c};this.neverQueue=function(){g=d};this.push=function(a){g(a);return a};this.run=function(){f=!0;b()};this.applyListener=function(a){var b,f;b=h;for(f=e.length;b<f;b++)e[b].listen(a)};this.toString=function(){return"Group[name="+a+"; working="+m+"; running="+f+"]"}}function S(a,c){return{"engine:listen":function(d){d.listen(new ha(a,
c))}}}function T(a){function c(a){return g[a]||(g[a]=new R(a))}function d(a){return b.addToGroup(a,b.newEngine())}var b=this,g={undefined:new R(void 0)},e=[];g.undefined.neverQueue();b.addGlobalListener=function(a){e.push(a);q(g,function(b,m){m.applyListener(a)})};b.addToGroup=function(a,b){q(e,function(a){b.listen(a)});return c(a).push(b)};b.newEngine=function(){return new P(a)};b.group=function(a){return d(a)};b.listen=function(){return d().listen.apply(null,arguments)};b.script=function(){return d().script.apply(null,
arguments)};b.wait=function(){return d().wait.apply(null,arguments)};b.run=function(a){c(a).run()};b.alwaysQueue=function(a){c(a).alwaysQueue()};b.neverQueue=function(a){c(a).neverQueue()};b.setOptions=function(){return d()}}function K(a){function c(a){var b,m;a=a.split(/; ?/);g={};for(var l=0,c=a.length;l<c;l++){m=a[l];b=m.indexOf("=");var d=g,e=m.slice(0,b);b=m.slice(b+1);b=unescape(b);d[e]=b}}function d(b,f,m){if(b){m=m||{};b=[b+"="+N(f||"")];if((f=m.expires)||0===f)n.isNumber(f)&&(f=(new Date(f)).toGMTString()),
b.push("expires="+f);(f=m.path)&&b.push("path="+f);(f=m.domain)&&b.push("domain="+f);!0===m.secure&&b.push("Secure");!0===m.httponly&&b.push("HttpOnly");m=b.join(";");if(m.length<e)a.cookie=m;else throw{name:"CookieTooLongError",message:"Cookie reached 4096 byte limit"};c(a.cookie)}}function b(a,b){d(a,"",s(b||{},{expires:1}))}var g={},e=4096;c(a.cookie||"");return{get:function(a){return g[a]},set:d,remove:b,findEach:function(a,b){for(var m in g)g.hasOwnProperty(m)&&m.match(a)&&b(m,g[m])},clear:function(a){var f=
s({},g),m;for(m in f)b(m,a)}}}function U(a){a=K(a);var c=a.set,d=a.remove;a.set=function(a,d,e){e=s(e||{},{path:"/"});0===e.expires&&(e.expires=+new Date("1/1/2038"));c(a,d,e)};a.remove=function(a,c){d(a,s(c||{},{path:"/"}))};a.purge=function(){};return a}function V(a,c){function d(a){a=a.expires;return 0!==a&&a<=+new Date}function b(b,f){a.setItem(b,f)}function g(a,b,f){b={value:b,expires:f};d(b)||c.setItem(a,JSON.stringify(b))}function e(a){a=c.getItem(a);try{return a?JSON.parse(a):void 0}catch(b){}}
function h(a){a=e(a);var b;return a&&(a.hasOwnProperty("value")&&a.hasOwnProperty("expires"))&&!d(a)?(b=a.value,delete a.value,[b,a]):[]}function f(a,b,f,c){for(var d,e=0,h=a.length;e<h;e++)d=a.key(e),!f[d]&&(f[d]=d.match(b))&&c(d)}return{set:function(a,f,c){a&&null!=f&&(c=c||{},(null!=c.expires?g:b)(a,f,c.expires))},get:function(b){return a.getItem(b)||h(b)[0]},findEach:function(b,d){var e={};f(a,b,e,function(b){var f=a.getItem(b);null!=f&&d(b,f)});f(c,b,e,function(a){var b=h(a),f=b[0],b=b[1];null!=
f&&d(a,f,b)})},remove:function(b){a.removeItem(b);c.removeItem(b)},purge:function(){for(var a,b,f=c.length;f--;)a=c.key(f),(b=e(a))&&(b.hasOwnProperty("value")&&b.hasOwnProperty("expires"))&&d(b)&&c.removeItem(a)}}}function F(a,c){var d={};d.set=a.set;d.findEach=function(b,d){var e={};a.findEach(b,function(a,b,c){e[a]=!0;d(a,b,c)});c.findEach(b,function(b,f,c){e[b]||(a.set(b,f,c),d(b,f,c))})};d.get=function(b){var d=a.get(b);void 0===d&&(d=c.get(b),void 0!==d&&a.set(b,d));return d};d.remove=function(b){a.remove(b);
c.remove(b)};d.purge=function(){a.purge();c.purge()};return d}function G(a){function c(a){var b={};if(!n.isString(a))return a;q(a.split("&"),function(a){if(""!==a){var f=a.split("=");a=decodeURIComponent(f[0]);f=f[1]&&decodeURIComponent(f[1].replace(/\+/g," "));(null==b[a]?b[a]=[]:b[a]).push(f)}});return b}function d(a,b){var c=[];q(a,function(a){if(n.isObject(a))return!1;a=null==a||""===a?b:a;(n.isString(a)||n.isNumber(a)||n.isBoolean(a))&&c.push(a)});return c}function b(a){return!n.isArray(a)?[a]:
a}function g(a,b){var c=encodeURIComponent(a),d=encodeURIComponent(b);return c+"="+d}var e=this,h={};s(h,c(a));e.param=function(a){a=h[a]||[""];return 1<a.length?a:a[0]};e.params=function(){return h};e.appendParam=function(a,c){if(a){var e=d(b(c));0<e.length&&(h[a]=(null==h[a]?h[a]=[]:h[a]).concat(e))}return this};e.replaceParam=function(a,c){if(a){var e=d(b(c));0<e.length&&(h[a]=(h[a]=[]).concat(e))}return this};e.appendParams=function(a){q(a,e.appendParam);return this};e.alwaysAppendParam=function(a,
c){if(a){var e=d(b(c),"");0<e.length&&(h[a]=(null==h[a]?h[a]=[]:h[a]).concat(e))}return this};e.alwaysReplaceParam=function(a,c){if(a){var e=d(b(c),"");0<e.length&&(h[a]=(h[a]=[]).concat(e))}return this};e.alwaysAppendParams=function(a){q(a,e.alwaysAppendParam);return this};e.appendPartialQueryString=function(a){a&&e.alwaysAppendParams(c(a));return this};e.deleteParam=function(a){delete h[a]};e.toString=function(){var a=[];q(h,function(b,c){q(c,function(c){a.push(g(b,c))})});return a.join("&")}}function B(a){function c(){var a=
k.toString();return h+f+(0<a.length?"?"+a:"")}var d={},b,g,e,h,f,m,l,u,v,k,r=a.match(ia);a=r[1]||"";g=r[2]||"";e=(r[3]||"").substring(1);b=g+(e?":"+e:"");h=a+(b?"//"+b:"");f=r[4]||"";m=(l=f.match(/^(.+?)?\/([^\/]+)?$/))&&l[1]||"";l=l&&l[2]||"";u=(r[5]||"").substring(1);v=(r[6]||"").substring(1);k=new G(u);s(d,k);s(d,{origin:h,scheme:a,host:b,hostname:g,port:e,path:f,pathname:m,scriptname:l,queryString:k.toString,fragment:function(){return v},tooLong:function(){return 2082<c().length},asString:c});
d.toString=c;return d}function W(a,c,d){function b(){var b=d.createEvent("Event");b.initEvent(c,!0,!1);try{b.currentTarget=b.target=a}catch(e){bt_log("warning: can not set target for ["+c+"] event: "+e)}return b}function g(){var a=d.createEventObject("Event");a.type=c;a.cancelable=!0;a.bubbleable=!1;return a}function e(d){setTimeout(function(){try{(d.handleEvent||d).call(a,h?b():g())}catch(e){bt_log("error: overriding ["+c+"] event: "+e)}},0)}var h=!!a.addEventListener,f=h?"addEventListener":"attachEvent",
m=a[f];a[f]=function(b,d,f){if(d&&("function"==typeof d||"function"==typeof d.handleEvent))if(b==c||b=="on"+c)e(d);else try{h?m.call(a,b,d,f):m(b,d)}catch(g){bt_log("error: proxying ["+b+"] event: "+g)}}}function X(a,c,d){function b(a){a.hasOwnProperty("enabled")&&(u=a.enabled);a.hasOwnProperty("timestamp")&&(A=a.timestamp,u=!0);a.hasOwnProperty("site")&&(m=a.site);a.hasOwnProperty("referrer")&&(l=a.referrer)}function g(d){d&&b(d);k=[];a.remove(c)}function e(){try{return JSON.stringify({site:m,referrer:l,
errors:k})}catch(a){bt_log("problem serializing errors: "+a.message)}return null}function h(a){var b=n.isObject(a)?s({},a):{};b.type=b.type||"unknown";b.message=b.message||a.toString();b.timestamp=A;return b}function f(){g();k.push(h({type:"runtime",message:"Too many errors"}));a.set(c,e())}if(!a)throw Error("ErrorManager requires a store");var m,l,u=!0,k=[],A=+new Date;d&&b(d);return{configure:b,reset:g,hasErrors:function(){return 0<k.length},tooManyErrors:f,processStoredErrors:function(){var b=
a.get(c);if(b)try{var d=JSON.parse(b)||{};m=d.site;l=d.referrer;n.isArray(d.errors)&&(k=k.concat(d.errors))}catch(e){bt_log("problem reading stored errors: "+e.message)}},push:function(b){bt_log("error: "+JSON.stringify(b));if(u&&b&&!(-1>b.tagId||-1>b.pageId))try{k.push(h(b)),a.set(c,e())}catch(d){if("CookieTooLongError"!=d.name)throw d;f()}},toJSON:e,toArray:function(){return k}}}function ja(a,c){return new function(a,b){function c(a){l.wait(a)}function e(a){function b(){m=k.jQuery;c(a)}f="var $ = BrightTag.$; ";
k.jQuery?b():l.script(k.instance.baseUri()+"BrightTag.jquery-1.5.1.js").wait(b)}var h={},f="",m,l=k.Blab.group(b);h.getJQuery=function(){return m};h.ensureJQuery=function(f){h.ensureJQuery=c;m=a.jQuery;(m?c:e)(f);k.Blab.run(b)};h.functionWithAccess=function(a,b){return new Function(a,f+b)};return h}(a,c)}function Y(a){function c(a,c){c&&c.findEach(a,function(a,c){b.appendParam(a,c)})}function d(a,b){return function(c){bt_log("invalid "+a+" expression: "+b+", exception = "+c)}}var b=this,g=a.window,
e=a.parentReferrer,h=a.referrer,f=B(0===a.host.length?"":(/^[a-z0-9+.-]+:\/\/.+/.test(a.host)?"":"//")+a.host+"/tag");s(b,f);b.toString=f.toString;b.appendParams({site:a.site,referrer:h,docReferrer:a.docReferrer,mode:a.mode,H:O(h||a.document.location.href)});h!==e&&b.appendParam("parentReferrer",e);c(/^btps\..+/,new K(a.document));c(/^btpdb\..+/,a.store);b.appendData=function(a){var c=bt_data(a),c=n.isArray(c)||n.isObject(c)?g.JSON.stringify(c):c;return b.alwaysReplaceParam("_cb_"+("bt_data('"+a+
"')"),c)};b.appendJs=function(a){var c=d("client binding expression",a);return b.alwaysReplaceParam("_cb_"+a,w(a,c))};b.cf=function(a){n.isArray(a)||(a=[a]);var c=b.param("cf");c&&(a=Array(c).concat(a));b.replaceParam("cf",a.join());return b};b.addCf=function(a,c){if(!w(c,d("conditional fire",c,"tags/"+a+"-cf.js")))return!1;var e=b.param("cf");b.replaceParam("cf",e?e+","+a:a);return!0};var m=b.toString();b.hasConditions=function(){return m!=b.toString()}}function Z(a,c){function d(a,b){q(b,function(b,
c){a[a.type+"."+b]=c});c.push(a)}function b(a,b,c){var d=k.instance.serverURL();q(a,function(a){a.trigger(b,c,d)});d.hasConditions()&&k.Blab.script(d.asString())}function g(a,c,e){function h(b,c){q(l,function(f){var h,g=f.name;try{h=k[f.dbe];if(!h){var l=k,r=f.dbe,v,q=f.dbe,n=y("event-dbes/"+g+"-page-"+(E||"adhoc")+"-event-"+a);v=m.functionWithAccess(["eventObject","eventData"],"return "+q+";"+n);h=l[r]=v}e.data(g,h.call(b.target,b,c))}catch(s){d({type:"evdbe",message:s.toString(),pageId:E||-1},{name:g,
eventName:a})}})}var g={},l=[],k={},E=(c||{}).pageId;g.data=function(a,b){l.push({name:a,dbe:b});return g};g.applyDataBindings=h;g.handler=function(c){var d,e=f[a];e&&0<e.length&&(d=Array.prototype.slice.call(arguments,1),h(c,d),b(e,c,d))};return g}function e(a){function b(a){0<l.length&&(a.cf(l),q(k,function(b){a.appendData(b)}),q(Q,function(b){a.appendJs(b)}))}function c(a,b){return function(c){bt_log("Invalid "+a+" expression: "+b+", exception = "+c)}}var e={},f={},h,g,l=[],k=[],Q=[];e.execute=
function(b,c){s(f,c||{});if(n.isFunction(b))g=b;else if(n.isString(b))a:{try{var h=y("events/"+a+"-tag-"+(f.tagId||"adhoc"));g=m.functionWithAccess(["eventObject","eventData"],b+h);break a}catch(l){d({type:"evparse",message:l.toString(),tagId:f.tagId||-1},{eventName:a})}g=void 0}else bt_log("when.execute: unknown action: "+b);return e};e.evaluate=function(a){h=a;return e};e.fire=function(a){l.push(a);return e};e.appendData=function(a){k.push(a);return e};e.appendJs=function(a){Q.push(a);return e};
e.trigger=function(e,m,l){var k=c("post-event conditional fire",h);if(!h||w(h,k)){try{g&&g.call(e.target,e,m)}catch(ga){d({type:"evwait",message:ga.toString(),tagId:f.tagId||-1},{eventName:a})}b(l)}};return e}var h={},f={},m=ja(a,"BrightTag.jQuery"),l=/^direct\//i;h.executeActions=b;h.Binder=g;h.bind=function(a,b,c,d){var e=g(a,d,k.instance);m.ensureJQuery(function(){var a=m.getJQuery(),d=a(b);if(n.isString(b)&&!l.test(c)&&(d.on||d.live))if(d.on)a(document).on(c,b,e.handler);else d.live(c,e.handler);
else d.bind(c.split(l).pop(),e.handler)});return e};h.EventAction=e;h.when=function(a){var b=e(a),c=f[a];c||(c=f[a]=[]);c.push(b);return b};return h}function ka(a,c,d,b){function g(b,c,e){var h=a.group(e).options(c||{});h.wait(function(){d.process(h,b)})}var e=!1,h={};h[b]=!0;return{tag:function(c,d){var l;l=d&&d.group;l=!e&&!l?b:l;g(c,d,l);l&&void 0===h[l]&&(h[l]=!0,e&&a.run(l))},run:function(){a.addGlobalListener(S(c,d));e=!0;q(h,a.run)}}}function $(a,c){function d(a){q(n.isArray(a)?a:[a],function(a){n.isFunction(a)?
a():v.write('<script type="text/javascript" src="'+a+'">\x3c/script>')})}function b(a){var b=r.group().options({tagId:-2});q(n.isArray(a)?a:[a],function(a){(n.isFunction(a)?b.wait:b.script)(a)})}function g(a){v.write(a)}function e(a,b){E.tag(a,b)}function h(a){l.writeScript=a?d:b;l.appendContent=a?g:e}function f(a){q(a,function(a){if(a.name){var b=s({},a);delete b.name;delete b.value;t.set(a.name,a.value,b)}})}function m(b){p.hasErrors()&&(b.appendParam("errors",p.toJSON()),b.tooLong()&&(b.deleteParam("errors"),
p.tooManyErrors(),b.appendParam("errors",p.toJSON())));p.reset({site:a.site,referrer:a.referrer||v.location.href})}var l=this,u=a.data||{},v=a.document||{},A=a.window||{},r=a.blab||k.Blab,p=a.errorManager,t=a.store,z=aa(v),E=a.asyncTagManager||ka(r,v,z,"domready");l.referrer=a.referrer;l.parentReferrer=a.parentReferrer;l.docReferrer=a.docReferrer;l.site=a.site;l.host=a.host;l.loadOnly=!!a.loadOnly;p&&r.addGlobalListener(new ba(p));r.run("serializer");l.load=function(){var a=Array.prototype.slice.call(arguments,
0);q(a,function(a){n.isFunction(a)?r.addToGroup("serializer",r.newEngine().wait(function(){a(l)})):n.isObject(a)&&a.src?l.library(a.src,a.options):n.isString(a)&&l.library(a)})};l.library=function(a,b){r.addToGroup("serializer",r.newEngine().options(b||{}).script(a))};h(x(a.mode,"sync"));l.domReady=function(){x(a.mode,"sync")&&h(!1);E.run()};l.parameter=function(a){return window.bt_parameter(a,v)};l.meta=function(a){return window.bt_meta(a,v)};l.cookie=function(a){return window.bt_cookie(a,v)};l.data=
function(a,b){if(void 0!==b)return u[a]=b;b=u[a];return null==b?"":b};l.dbe=function(a,b,c){function d(b){p&&p.push({type:"dbe",message:b.toString(),"dbe.name":a,pageId:(c||{}).pageId||-1})}null==u[a]&&l.data(a,w(b,d,"page-dbes/"+a+"-page-"+(c&&c.pageId||"adhoc")))};l.errors=function(a){p.configure(a)};l.store=t?f:function(){};l.serverURL=function(){return new Y(a)};l.defaultBaseUri=function(){return("https:"==v.location.protocol?"https:":"http:")+"//s.btstatic.com/"};l.baseUri=function(){var a=/\btag(\.[^.]+|-n)?\.js(#.*)?$/;
return c&&c.src&&c.src.replace(a,"")||l.defaultBaseUri()};l.primary=function(){function a(){var b=l.serverURL();p&&(p.processStoredErrors(),m(b));return b.toString()}var b=[];A.JSON?b.push(a()):(b.push(l.baseUri()+"json2.js"),b.push(function(){l.writeScript(a())}));l.writeScript(b)};l.secondary=function(a){var b=l.serverURL(),c=b.toString();a(b);b.toString()!=c&&(p&&m(b),l.writeScript(b.toString()))}}function C(){var a={},c={};return{on:function(c,b){var g=a[c];g||(g=a[c]=[]);g.push(b)},once:function(a,
b){var g=c[a];g||(g=c[a]=[]);g.push(b)},emit:function(d){function b(a){a.apply(this,g)}var g=Array.prototype.slice.call(arguments,1);q(a[d],b);q(c[d],b);c[d]=[]}}}function la(a){function c(a){return null!=g[a]}function d(a,b){void 0!==b&&(g[a]=b);var c=g[a];return null==c?"":c}var b,g=s({},a);return b=s({dbe:function(a,h,f){if(!c(a)&&(h=w(h,function(c){b.emit("error",c,a,f)}),null!=h))return d(a,h)},data:d,hasData:c},C())}function ma(a){var c,d={},b=["eventObject","eventData","$","bt_data"];return c=
s({dbe:function(a,e){try{d[a]=new Function(b,"return "+e+";")}catch(h){h.type="evdbe",c.emit("error",h,a)}return c},trigger:function(b,e,h){var f=b.target,m=[b,e,h,a.data];q(d,function(b,d){try{a.data(b,d.apply(f,m))}catch(e){e.type="evdbe",c.emit("error",e,b)}})}},C())}function na(a){function c(a,c){c.type=a;b.emit("error",c)}function d(a){g.push(a);return b}var b,g=[],e=function(){return!0},h=["eventObject","eventData","$","bt_data"];return b=s({fire:function(a){return d(function(b){b.fire(a)})},
appendData:function(a){return d(function(b){b.appendData(a)})},appendJs:function(a){return d(function(b){b.appendJs(a)})},execute:function(e){function g(b,d,e,f){try{v.call(d.target,d,e,f,a.data)}catch(h){c("evwait",h)}}var l;if(n.isString(e))a:{try{l=new Function(h,e);break a}catch(k){c("evparse",k)}l=void 0}else l=e;var v=l;return v?d(g):b},evaluate:function(c){var d=new Function(h,"return "+c);e=function(b,c,e,f){return d.call(c.target,c,e,f,a.data)};return b},trigger:function(a,b,c,d){e(a,b,c,
d)&&q(g,function(e){e(a,b,c,d)})}},C())}function oa(a){var c=/^direct\//i,d=!1;return{bind:function(a,d,e){function h(a){var b=Array.prototype.slice.call(arguments,1);e(a,b,k.jQuery||window.jQuery)}var f=k.jQuery||window.jQuery,m=f(a),l=c.test(d);if(!l&&m.on)f(document).on(d,a,h);else!l&&m.live?m.live(d,h):m.bind(d.split(c).pop(),h)},newBinder:function(a){return ma(a)},newHandler:function(a){return na(a)},ensureLibrary:function(b){k.jQuery||window.jQuery?b():(d||(d=!0,a.run()),a.wait(b))}}}function pa(a,
c){function d(b,c,d,m){var l=L(a);q(b,function(a){a.trigger(l,c,d,m)});g.emit("triggered",l)}var b={},g=C();return s(g,{bind:function(e,h,f,m){function l(a,c,f){k.trigger(a,c,f);d(b[e],a,c,f)}var k=c.newBinder(a,e);k.on("error",function(a,b){g.emit("error",a,{name:b,eventName:e},m)});c.ensureLibrary(function(){c.bind(h,f,l)});return k},handle:function(d,h){var f=c.newHandler(a);f.on("error",function(a){g.emit("error",a,{eventName:d},h)});b[d]=b[d]||[];b[d].push(f);return f}})}function aa(a){function c(a,
b){a.src?b.preemptScript(a.src,a.innerHTML):a.innerHTML&&b.preemptWait(a.innerHTML)}function d(b){try{a.body.appendChild(b.cloneNode(!0))}catch(c){bt_log("error appending content to body: "+c)}}var b=a.createElement("div");return{process:function(a,e){if(0!==e.length){b.innerHTML="<br/>"+e;for(var h=b.childNodes||[],f=1,m=h.length;f<m;f++)("SCRIPT"==h[f].tagName?c:d)(h[f],a)}}}}function qa(a){function c(b){a.write(b);return d}var d={tag:c,script:function(a){return c('<script type="text/javascript" src="'+
a+'">\x3c/script>')},wait:function(a){a();return d}};return d}function ra(a,c){function d(c,d){var f=c&&c.group;d(a.group(f).options(c||{}));f&&void 0===b[f]&&(b[f]=!0,a.run(f))}var b={},g={tag:function(a,b){d(b,function(b){b.wait(function(){c.process(b,a)})});return g},script:a.script,wait:a.wait};return g}function sa(a,c){var d=c;return{tag:function(a,c){return d.tag(a,c)},script:function(a){return d.script(a)},wait:function(a){return d.wait(a)},sync:function(){d=a},async:function(){d=c}}}function ba(a){return{dbe:function(c,
d,b){a.push({type:"dbe",message:c.toString(),"dbe.name":d,pageId:(b||{}).pageId||-1})},events:function(c,d,b){var g=c.type,e="evdbe"===g?"pageId":"tagId",h={type:g,message:c.toString()};q(d,function(a,b){h[g+"."+a]=b});h[e]=(b||{})[e]||-1;a.push(h)},"block:error":function(c,d){var b,g,e;d&&(b=d.type,g=d.exception||d,e=c.option("tagId")||-1,a.push({type:b,message:g.toString(),tagId:e}))}}}function ta(a){function c(){var b=new B(a.src),c={},d=b.fragment();c.staticHost=b.host+b.pathname;d&&q((new G(d)).params(),
function(a,b){c[a]=1<b.length?b:b[0]});return c}function d(){var b=t(a.innerHTML);return 0===b.length?{}:w("(\n"+b+"\n)",function(a){bt_log("json configuration error: "+a)})}return{isTagjs:function(){return/\/tag(\.[^.]+|-n)?\.js(\?.*)?(#.*)?$/.test(a.src)},toJSON:function(){return s(c(),d())},script:a}}function ua(a){return{isTagjs:function(){return!0},toJSON:function(){return a||{}},script:{src:void 0}}}function ca(){function a(){return c}var c;return c={fire:a,appendData:a,appendJs:a,execute:a,
when:a}}function L(a){function c(a,b){for(var c in a)if(b(c,a[c]))return!0;return!1}var d,b=[],g={};return d={toJSON:function(){var a=0<b.length?{cf:b.join()}:{};return s(a,g)},fire:function(a){a=M(a,function(a){return null!=a&&""!==a});b=b.concat(a);return d},appendData:function(b){g["_cb_bt_data('"+b+"')"]=a.data(b);return d},appendJs:function(a){g["_cb_"+a]=w(a);return d},execute:function(a){a();return d},when:function(b){var c;try{return c=new Function(["bt_data"],"return "+k.trim(b)),c(a.data)?
d:ca()}catch(f){bt_log("conditional evaluation error: ["+f.toString()+"] while evaluating ["+b+"]")}return ca()},hasConditions:function(){return 0<b.length||c(g,function(a,b){return null!=b})}}}function va(a,c,d,b,g,e){function h(){z=!0;c.async();r.mode=M(r.mode,function(a){return"sync"!==a})}function f(a){null==window.JSON?c.script(B(r.staticHost+"/json2.js")).wait(a):a()}function m(a){if(null==a||a.hasConditions())b.reset({site:r.site,referrer:r.referrer||window.location.href})}function l(a){var c=
B("//"+t+"/tag").appendParams({site:r.site,mode:r.mode,H:r.H,referrer:r.referrer,docReferrer:r.docReferrer}).alwaysAppendParams(a);g.findEach(RegExp("^btp(s|db)\\."+r.site+"\\..+"),function(a,b){c.appendParam(a,b)});return c.appendParams({errors:b.hasErrors()?b.toJSON():null})}function k(a){if(null==a)return l();if(a.hasConditions())return l(a.toJSON())}function p(a){var d=k(a);d?(d.tooLong()&&(b.tooManyErrors(),d=k(a)),m(a),c.script(d.toString())):m(a)}var n,r=s({},e),t=r.host||"",w=C(),z=!1;d.on("triggered",
p);return n=s({config:r,diagnostic:function(a){a&&(r.diagnostic=a,n.emit("diagnostic",a))},errors:function(a){b.configure({timestamp:a})},dbe:function(b,c,d){var e=a.dbe(b,c,d);null!=e&&n.emit("dbe",b,c,e,d)},data:a.data,dataref:function(a){return null==a?"":'BrightTag.site("'+r.site+'").data("'+a.replace(/"/g,"\\x22")+'")'},store:function(a){q(a,function(a){if(a.name){var b=s({},a);delete b.name;delete b.value;g.set(a.name,a.value,b)}})},tag:function(a,b){n.emit("tag",a,b);return c.tag(a,b)},script:c.script,
wait:c.wait,events:{bind:function(a,b,c,e){n.emit("event-binding",a,b,c,e);return d.bind(a,b,c,e)},on:d.handle},when:function(b,c){L(a).when(b).execute(function(){c(n)});return n},domready:function(a){if(null==a)h();else w.once("domready",a);z&&w.emit("domready",n)},primary:function(){f(function(){b.processStoredErrors();p()})},secondary:function(b){var c=L(a);b(c);p(c)}},C())}function wa(a){a=B(a.staticHost+"/BrightTag.jquery-1.5.1.js");return oa((new P(document)).script(a))}function xa(a,c,d){var b=
qa(document);a=ra(a,c);b=sa(b,a);x(d.mode,"sync")&&b.sync();return b}function ya(a){var c,d,b,g,e,h,f,m;if((f=a.site)&&!H[f])return c=la(a.data),d=new T(document),m=aa(document),b=xa(d,m,a),e=pa(c,wa(a)),h=X(D?F(D,I):I,"__bterr_"+f,{enabled:!1}),g=ba(h),c.on("error",g.dbe),e.on("error",g.events),d.addGlobalListener(g),k.Events.onDOMReady(function(){d.addGlobalListener(S(document,m))}),a=H[f]=va(c,b,e,h,D?F(I,D):I,a)}function da(a,c,d){try{var b,g,e=a.toJSON();if(!(k.instance&&k.instance.site===e.site)){var h=
s({host:"s.thebrighttag.com",staticHost:"s.btstatic.com",H:O(e.referrer||c.location.href),docReferrer:c.document.referrer},e);b=ya(h);if(e.site&&!k.instance&&!ea&&!x(e.mode,"v2")&&!x(e.mode,"v2b")){var f=a.script,m=fa();k.EventBinding=Z(m.window,m.errorManager);k.instance=new $(s(m,e),f);g=k.instance;b.config.loadOnly=!0}else if(b){var l=b.config,n;var p=b.config.mode;n=x(p,"v2")?p:!p?"v2":["v2"].concat(p);l.mode=n}d&&d(b,g);return b}}catch(q){bt_log("error configuring site ["+a.script.src+"]: "+
q)}}function za(a){var c,d,b=[];if(n.isArray(a))b=a.slice(0);else{c=0;for(d=a.length;c<d;c++)b.push(a[c])}return b}function Aa(a){if(!ea&&!x(a.config.mode,"v2")&&!x(a.config.mode,"v2b"))k.Events.onDOMReady(function(){a.domready()});else a.config.loadOnly||(k.Events.onDOMReady(function(){a.domready()}),a.primary())}function fa(){var a,c=U(document),d=c,b=c;try{window.localStorage&&window.sessionStorage&&(a=V(sessionStorage,localStorage),a.purge(),d=F(c,a),b=F(a,c))}catch(g){bt_log("Unable to access DOM storage: "+
g)}return{id:Math.random(),loadOnly:!1,window:window,document:document,host:"s.thebrighttag.com",parentReferrer:top!=self&&self.window?self.window.location.href:null,docReferrer:document.referrer,data:{},store:d,errorManager:X(b,"__bterr")}}if(k)return k;var ea=!1;k={};var n={isString:function(a){return p(a,"String")},isArray:function(a){return p(a,"Array")},isNumber:function(a){return p(a,"Number")},isBoolean:function(a){return p(a,"Boolean")},isFunction:function(a){return p(a,"Function")},isObject:function(a){return null===
a||void 0===a?!1:p(a,"Object")}},w=bt_eval,ha=function(){function a(){}function c(a,b,c){try{a[b]=c}catch(d){bt_log("warning: could not assign value to 'document."+b+"': "+d)}}var d,b=[],g=function(a){d.push(a)};return function(e,h){var f;this["block:start"]=function(){b.push([d,e.write,e.writeln,e.open,e.close]);d=[];c(e,"write",g);c(e,"writeln",g);c(e,"open",a);c(e,"close",a)};this["block:finish"]=function(){try{h.process(f,d.join(""))}finally{var a=b.pop();d=a[0];c(e,"write",a[1]);c(e,"writeln",
a[2]);c(e,"open",a[3]);c(e,"close",a[4])}};this["engine:listen"]=function(a){f=a}}}(),ia=/^(?:([^:\/]+:)?\/\/)?([^:\/?#]+)?(:[0-9]+)?([^?#]*)(\?[^#]*)?(#.*)?$/,H={},D,I=U(document);try{window.localStorage&&window.sessionStorage&&(D=V(sessionStorage,localStorage),D.purge())}catch(Ba){bt_log("Unable to access DOM storage: "+Ba)}k.Escaper={cookie:N,javascript:function(a){return!n.isString(a)?a:a.replace(/\\/g,"\\\\").replace(/'/g,"\\x27").replace(/"/g,"\\x22").replace(/\n/g,"\\n").replace(/\r/g,"\\r")}};
k.Random={integer:function(a){return Math.floor(Math.random()*(a||1E8))}};k.pushIfDefined=function(a,c,d){a&&(a.constructor==Array&&null!=c)&&a.push(d||c)};k.ServerURL=Y;k.Main=function(a){function c(b){(b=(new B(b.src)).fragment())&&q((new G(b)).params(),function(b,c){a[b]=c[0]})}function d(b){function c(a){bt_log("configuration error: "+a)}b=t(b.innerHTML);0!==b.length&&s(a,w("(\n"+b+"\n)",c,"site-config"))}var b,g=function(){var b,c,d=/\/tag(\.[^.]+|-n)?\.js(#.*)?$/,e=a.document.getElementsByTagName("script");
for(b=e.length-1;-1<b;b--)if(c=e[b],d.test(c.src))return c}();g&&(c(g),d(g));if(null!=a.site){k.Events.enablePageReadyOverrides();try{b=new $(a,g),k.Events.onDOMReady(b.domReady),b.loadOnly||b.primary()}catch(e){bt_log("execution error: "+e)}return b}};k.CookieSync={pushImage:function(a){(new Image).src=a;throw"CookieSync.pushImage no longer supported ["+a+"]";},pushIframe:function(a){throw"CookieSync.pushIframe no longer supported ["+a+"]";}};k.EventBindingManager=Z;k.defaultConfig=fa;k.Types=n;
k.trim=t;k.each=q;k.extend=s;k.eval=w;k.HTTP={Cookie:K,QueryString:G,URL:B};k.Blab=new T(document);k.Events=new function(a,c){function d(){}function b(a,b,c){a[r](t+b,c,!1)}function g(a,b,c){a[s](t+b,c,!1)}function e(){var a=c.readyState;if("loading"==a)return!1;if("complete"==a)return!0;a:{try{w("left")}catch(b){a=!1;break a}a=!0}return a}function h(a,b,c){var d=this;setTimeout(function(){a()?b.call(d):h(a,b,c)},c)}function f(){f=d;n&&W(c,p,c)}function k(){f();W(a,q,c)}var l=this,n=!!a.addEventListener,
p="DOMContentLoaded",q="load",r=n?"addEventListener":"attachEvent",s=n?"removeEventListener":"detachEvent",t=n?"":"on",w=c.documentElement.doScroll||function(){throw"No doScroll";};l.listen=b;l.unlisten=g;l.onDOMReady=function(d){e()?d.call(this):c.addEventListener?(b(c,p,d),b(c,p,function(){g(a,q,d)}),b(a,q,d)):h(e,d,1)};l.enablePageReadyOverrides=function(){l.enablePageReadyOverrides=d;e()?k():(n&&b(c,p,f),b(a,q,k))}}(window,document);k.Events.enablePageReadyOverrides();k.site=function(a,c){try{var d=
H[a];d&&c&&c(d);return d}catch(b){bt_log("error while executing site configuration ["+a+"]: "+b)}};k.configureNewSites=function(a,c){q(za(a.document.getElementsByTagName("script")),function(d){d=ta(d);d.isTagjs()&&da(d,a,c)})};k.configureSite=function(a,c,d){return da(ua(a),c,d)};k.configuredSites=function(){var a=[];q(H,function(c,d){a.push(d)});return a};k.initializeSite=function(a,c){c&&(k.Events.onDOMReady(c.domReady),c.loadOnly||c.primary());a&&Aa(a)};return k}(window.BrightTag);
(function(k){k.configureNewSites(window,k.initializeSite);null==k.instance&&setTimeout(function(){null==k.instance&&k.configureNewSites(window,k.initializeSite)},0)})(BrightTag);var _bt_url_prefix,_bt_referrer,_bt_site,_bt_mode;function btServe(k){var p=BrightTag,t={referrer:_bt_referrer,site:_bt_site,mode:_bt_mode};null!=_bt_url_prefix&&(t.host=_bt_url_prefix);p.configureSite(p.extend(t,k),window,p.initializeSite)};
